# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options

zeebe.client:
  broker.gatewayAddress:
zeebe:
  client:
    broker:
      gatewayAddress: dave03.gke.c8sm.com:443
    security:
      plaintext: false
    cloud:
      client-id: "ba4089db-c72a-4049-8fde-955179365ccf"
      client-secret: "7tB8Q~DXNton_.lTJkIs5AtXGgZnzsKUkILRoc4y"
      auth-url: "https://login.microsoftonline.com/cbd46654-4f74-4332-a490-69f0f071ba9f/oauth2/v2.0/token"
      scope: "ba4089db-c72a-4049-8fde-955179365ccf/.default"

# go to http://localhost:8084/applications/ and create application of type M2M with read/write access to Operate & Tasklist
identity.clientId: "ba4089db-c72a-4049-8fde-955179365ccf"
identity.clientSecret: "7tB8Q~DXNton_.lTJkIs5AtXGgZnzsKUkILRoc4y"
keycloakUrl: http://localhost:18080
tasklistUrl: "https://dave03.gke.c8sm.com/tasklist"
operateUrl: "https://dave03.gke.c8sm.com/operate"

# this is to allow react application launched separately to access the WS
websocket:
  allowedOrigin: "*"

springdoc.swagger-ui.path: /swagger-ui.html

spring:
  servlet.multipart:
    max-file-size: 10MB
    max-request-size: 30MB

  security.oauth2:
    enabled: false
    # client:
      # registration.customTaskList:
        # client-id: customTasklist
        # client-secret: lSmJzWhpzGyYKf3Zmo3vekJndcJ2EXu3
        # authorization-grant-type: authorization_code
        # scope: openid, profile
        # redirect-uri: http://localhost:8080/login/oauth2/code/customTaskList
      # provider.customTaskList.issuer-uri: http://localhost:18080/auth/realms/camunda-platform

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1048576

logging:
  level:
    root: INFO
