# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options

zeebe.client.cloud:
  region: bru-2
  clusterId: xxx
  clientId: xxx
  clientSecret: xxx
#zeebe.client:
#  broker.gatewayAddress: 127.0.0.1:26500
#  security.plaintext: true

identity.clientId: java
identity.clientSecret: foTPogjlI0hidwbDZcYFWzmU8FOQwLx0
tasklistUrl: https://bru-2.tasklist.camunda.io/xxx/graphql
operateUrl: https://bru-2.operate.camunda.io/xxx

baseUrl: http://localhost:8080

process.solution:
  allowedOriginPatterns: "*"

spring:
  datasource:
    url: jdbc:h2:file:./h2/db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1048576

logging:
  level:
    root: INFO
